import { Role, RoleId, Team } from '../types/game';

const baseRoles: Record<RoleId, Omit<Role, 'maxUses'> & { maxUses?: number }> = {
  mafia: {
    id: 'mafia',
    name: 'Mafia',
    team: 'mafia',
    description: 'Kills one player every night. Works with fellow mafia members.',
    nightAction: true,
    actionTarget: 'player',
    priority: 100,
    emoji: '🔪',
    maxUses: Infinity,
  },
  godfather: {
    id: 'godfather',
    name: 'Godfather',
    team: 'mafia',
    description: 'The mafia leader. Appears innocent to the Cop. Cannot be killed at night.',
    nightAction: true,
    actionTarget: 'player',
    priority: 110,
    emoji: '👔',
    maxUses: Infinity,
  },
  doctor: {
    id: 'doctor',
    name: 'Doctor',
    team: 'town',
    description: 'Can save one player from death each night.',
    nightAction: true,
    actionTarget: 'player',
    priority: 80,
    emoji: '💊',
    maxUses: Infinity,
  },
  cop: {
    id: 'cop',
    name: 'Cop',
    team: 'town',
    description: 'Can investigate one player each night to learn their alignment.',
    nightAction: true,
    actionTarget: 'player',
    priority: 90,
    emoji: '🔍',
    maxUses: Infinity,
  },
  detective: {
    id: 'detective',
    name: 'Detective',
    team: 'town',
    description: 'Can investigate one player each night to learn their exact role.',
    nightAction: true,
    actionTarget: 'player',
    priority: 85,
    emoji: '🔎',
    maxUses: Infinity,
  },
  medic: {
    id: 'medic',
    name: 'Medic',
    team: 'town',
    description: 'Can protect a player from death but cannot protect the same player twice in a row.',
    nightAction: true,
    actionTarget: 'player',
    priority: 75,
    emoji: '🩹',
    maxUses: Infinity,
  },
  vigilante: {
    id: 'vigilante',
    name: 'Vigilante',
    team: 'town',
    description: 'Can kill one player at night. Uses limited bullets.',
    nightAction: true,
    actionTarget: 'player',
    priority: 95,
    emoji: '🔫',
    maxUses: 2,
  },
  sniper: {
    id: 'sniper',
    name: 'Sniper',
    team: 'town',
    description: 'Can kill one player every other night.',
    nightAction: true,
    actionTarget: 'player',
    priority: 96,
    emoji: '🎯',
    maxUses: 3,
  },
  mayor: {
    id: 'mayor',
    name: 'Mayor',
    team: 'town',
    description: 'Your vote counts as 2. Can reveal yourself once to confirm your identity.',
    nightAction: false,
    actionTarget: 'self',
    priority: 0,
    emoji: '📜',
    maxUses: 1,
  },
  villager: {
    id: 'villager',
    name: 'Villager',
    team: 'town',
    description: 'No special abilities. Your voice and vote matter during the day.',
    nightAction: false,
    actionTarget: 'none',
    priority: 0,
    emoji: '👤',
    maxUses: 0,
  },
  serial_killer: {
    id: 'serial_killer',
    name: 'Serial Killer',
    team: 'neutral',
    description: 'Kills one player every night. Wins by being the last alive.',
    nightAction: true,
    actionTarget: 'player',
    priority: 105,
    emoji: '🩸',
    maxUses: Infinity,
  },
  jester: {
    id: 'jester',
    name: 'Jester',
    team: 'neutral',
    description: 'Wins only if lynched during the day. No night action.',
    nightAction: false,
    actionTarget: 'none',
    priority: 0,
    emoji: '🎭',
    maxUses: 0,
  },
  spy: {
    id: 'spy',
    name: 'Spy',
    team: 'neutral',
    description: 'Can observe one player each night to learn their role.',
    nightAction: true,
    actionTarget: 'player',
    priority: 70,
    emoji: '👁️',
    maxUses: Infinity,
  },
  witch: {
    id: 'witch',
    name: 'Witch',
    team: 'neutral',
    description: 'Has two potions: one to save, one to kill. Each used once.',
    nightAction: true,
    actionTarget: 'player',
    priority: 60,
    emoji: '🧙',
    maxUses: 2,
  },
  lovers: {
    id: 'lovers',
    name: 'Lover',
    team: 'lovers',
    description: 'Two lovers. If one dies, the other dies of heartbreak. Win together.',
    nightAction: false,
    actionTarget: 'none',
    priority: 0,
    emoji: '💕',
    maxUses: 0,
  },
};

export const ROLES: Record<RoleId, Role> = Object.entries(baseRoles).reduce(
  (acc, [key, val]) => {
    acc[key as RoleId] = { ...val, maxUses: val.maxUses ?? 0 } as Role;
    return acc;
  },
  {} as Record<RoleId, Role>
);

export const ROLE_ORDER: RoleId[] = [
  'godfather',
  'mafia',
  'serial_killer',
  'vigilante',
  'sniper',
  'cop',
  'detective',
  'doctor',
  'medic',
  'witch',
  'spy',
  'villager',
  'mayor',
  'jester',
  'lovers',
];

export const TEAM_NAMES: Record<Team, string> = {
  mafia: 'Mafia',
  town: 'Town',
  neutral: 'Neutral',
  lovers: 'Lovers',
};

export const TEAM_COLORS: Record<Team, string> = {
  mafia: '#dc2626',
  town: '#2563eb',
  neutral: '#9333ea',
  lovers: '#db2777',
};
